name: CI

on:
  push:
    paths-ignore:
      - '*.md'
      - 'docs/**'
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  test:
    uses: ./.github/workflows/REUSABLE_INTEGRATION.yml
