name: CI

on:
  push:
    paths-ignore:
      - '*.md'
      - 'docs/**'
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: env the env
        run: |
          set
