name: Manual Trigger

on:

  workflow_dispatch:
    inputs:
      redis_version:
        description: 'Redis Enterprise cluster version'
        default: '100.0.0-2938'
        required: true
        type: choice
        options:
          - 6.2.18-49
          - 6.2.12-82
          - 6.2.10-129
          - 6.2.8-53
          - 6.2.4-54
          - 6.0.20-101
          - 6.0.12-58
          - 6.0.8-32
          - 6.0.6-39
      redisearch_version:
        description: 'RediSearch version'
        required: false
        type: string
      redisjson_version:
        description: 'RedisJSON version'
        required: false
      redisbloom_version:
        description: 'RedisBloom version'
        required: false
      redisgraph_version:
        description: 'RedisGraph version'
        required: false
      redistimeseries_version:
        description: 'RedisTimeSeries version'
        required: false

jobs:

  test:
    uses: ./.github/workflows/REUSABLE_INTEGRATION.yml
    with:
      redis_version: ${{ inputs.redis_version}}
      redisearch_version: ${{ inputs.redisearch_version}}
      redisjson_version: ${{ inputs.redisjson_version}}
      redisgraph_version: ${{ inputs.redisgraph_version}}
      redisbloom_version: ${{ inputs.redisbloom_version}}
      redistimeseries_version: ${{ inputs.redistimeseries_version}}
