name: Integration

on:

  workflow_call:
    inputs:
      redis_version:
        default: '100.0.0-2938'
        required: false
        type: string
      redisearch_version:
        description: 'RediSearch version'
        required: false
        type: string
      redisjson_version:
        description: 'RedisJSON version'
        required: false
        type: string
      redisbloom_version:
        description: 'RedisBloom version'
        required: false
        type: string
      redisgraph_version:
        description: 'RedisGraph version'
        required: false
        type: string
      redistimeseries_version:
        description: 'RedisTimeSeries version'
        required: false
        type: string

jobs:

  integration:
    runs-on: ubuntu-latest
    services:
      redismod:
        image: redislabs/redismod:edge
        ports:
          - 6379:6379
    steps:
      - name: SHOW VERSIONS
        run: |
          echo redis-${{inputs.redis_version}} \
            search-${{inputs.redisearch_version}} \
            json-${{inputs.redisjson_version}} \
            graph-${{inputs.redisgraph_version}} \
            bloom-${{inputs.redisbloom_version}} \
            timeseries-${{inputs.redistimeseries_version}}

